### ISSUE TITLE
Type.Record Union Key Evaluation too Complex

### ISSUE THREAD

**Issue by Jackson-clipboard** [sinclairzx81/typebox#1208]
When given the following structure of where the union array length exceeds 46, we are presented with the error:
`Type instantiation is excessively deep and possibly infinite`

```typescript
// Length exceeds 46
const Schema = Type.Union([
Type.Literal('a'),
Type.Literal('b'),
Type.Literaly('c')
...
]);
```

Separating out the union array to be as follows, avoids the error:
```typescript
// Max length of 46
const Schema1 = Type.Union([
  Type.Literal('a'),
  Type.Literal('b'),
  Type.Literal('c'),
  // ...
]);

// Max length of 46
const Schema2 = Type.Union([
  Type.Literal('aa'),
  Type.Literal('bb'),
  Type.Literal('cc'),
  // ...
]);

const FullSchema = Type.Union([
  Schema1,
  Schema2
]);
```

**Comment by sinclairzx81** [comment]
@Jackson-clipboard Hi, 

I can't seem to reproduce this on the current version (0.34.30)

[TypeScript Link Here](https://www.typescriptlang.org/play/?noErrorTruncation=true#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUDP784AWiXKVqteo2at6qXLgA5COwUARYC2KcYu+drv2HdqUMxwAgnAC8eQsRIAeFwwIKncAPjg9KAwAEwBXEgw4GAg4djiuLikSIwt3LxRhADoAVXZgIwAKAG0pOELMIv0MrkqAShw0RubM9s7intaOhowmlr6Rsd7hrtHBidmpof7u8eG4Osn5mYG1lbm9rcPF7f2lhd3ps9PNk+PL5aOrp8e757fXh4vVq9uvnZ+n0B3wO73+13uwIBoOWfyhELB8JeIPO0NRCKBML6cKxaNOyLxkNxGJR+I+2Pq5MJiOJBJJ1Mx6LpOKZVPp7LpnLZnMi8n8Cjg4gAbAAWFlk8FcyXcmXS8HiomsuVI2Uq5XEhU0pVqnW01V6+WU9Xag26k3miXwzWMy2mu0WxW29HW0mOt1ap2e92wo1mr0e72ugPBn1Sv2BhlBm0RnB6fmCgCMACYABxSAC6bRsikcubz9mzZgsHBI1j0+YrldUzmEcAAQgV8ERSIFhCF6xEorEEkkUnBkym4AA3AhQYAEdjWHLsPIN7yLMoVdg1FkAGWAMAwUAIrQADGj15vt60EweN1ud5Uk2ej5eAMw3i+tEWP4+VACsr8vQq-rQA7B0a7nm+Ka-pUACcYEJvuZyHk+lQJqesHAZeyZQQ+yG3ieL6YfBCaflgQFYQhP64W+CYAWRqGgVRJ6QbRV4wZMcFvkmSHMShrRJteDFJhhRHwUmOEccRSYESJgmkRJrGUdJl6pmBSb0XJrR3kxiwsfeSECW+d48SplR3hhBl3sJGmcYZ4nmcRd5SdZ8F3rJ9m6TRJn0Tpl4iupxSac+7HOZ5+kBc+xnBZUIpmT5FkilZUXESKdlxfBIqUR5z6uWFIrKWF77eY0vkfv5SVvu+QXFZe76heVrTvpF+UWe+BFpR+iX1cR75OdVH4ZV177ZV1Qp5aMBVCkVbXwUKZXjW+QrGbycDxsKYq+sNFmimBQqxdN36tatxFCp122tEKPVHZUQr9Wdf5DUUBV-tpK23RZf5TXt8F-lVV11W9b5-ltP2Xn+u1PcRf6HQD-6nRDlR-u5j0FSmN0I2N0Mpq9IPwSmn2o99GMgf9eOXimwMI6l8MWSmUOE60KaXdD4FIxZ4Eo9TEHowV4HY6z4G4xzTXk8R4Ek0z4Pc1THN06z0GM8R0EswV0HsxZ0H8QLeG7rzyu7gTCu7sLsu7qLuvi1rksK9BUGIYBavkWhDGIVz5ua7L+GW-reEUZbJsu3DBnJjLeFsVB3HB47ytCcHOvh+75FJrJcYCuIA4Zm0QA)

```typescript
import { Type, Static } from '@sinclair/typebox'

// --------------------------------------------------------------
// Non-Distinct
// --------------------------------------------------------------
type A = Static<typeof A> // reduce to null
const A = Type.Union([
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),  
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),  // <- x64
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(),
  Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), Type.Null(), // <- x128
])
// --------------------------------------------------------------
// Distinct
// --------------------------------------------------------------
type B = Static<typeof B> // reduce to 128 variant
const B = Type.Union([
  Type.Literal(0), Type.Literal(1), Type.Literal(2), Type.Literal(3), Type.Literal(4), Type.Literal(5), Type.Literal(6), Type.Literal(7),
  Type.Literal(8), Type.Literal(9), Type.Literal(10), Type.Literal(11), Type.Literal(12), Type.Literal(13), Type.Literal(14), Type.Literal(15),
  Type.Literal(16), Type.Literal(17), Type.Literal(18), Type.Literal(19), Type.Literal(20), Type.Literal(21), Type.Literal(22), Type.Literal(23),
  Type.Literal(24), Type.Literal(25), Type.Literal(26), Type.Literal(27), Type.Literal(28), Type.Literal(29), Type.Literal(30), Type.Literal(31),
  Type.Literal(32), Type.Literal(33), Type.Literal(34), Type.Literal(35), Type.Literal(36), Type.Literal(37), Type.Literal(38), Type.Literal(39),
  Type.Literal(40), Type.Literal(41), Type.Literal(42), Type.Literal(43), Type.Literal(44), Type.Literal(45), Type.Literal(46), Type.Literal(47),
  Type.Literal(48), Type.Literal(49), Type.Literal(50), Type.Literal(51), Type.Literal(52), Type.Literal(53), Type.Literal(54), Type.Literal(55),
  Type.Literal(56), Type.Literal(57), Type.Literal(58), Type.Literal(59), Type.Literal(60), Type.Literal(61), Type.Literal(62), Type.Literal(63),  // <- x64
  Type.Literal(64), Type.Literal(65), Type.Literal(66), Type.Literal(67), Type.Literal(68), Type.Literal(69), Type.Literal(70), Type.Literal(71),
  Type.Literal(72), Type.Literal(73), Type.Literal(74), Type.Literal(75), Type.Literal(76), Type.Literal(77), Type.Literal(78), Type.Literal(79),
  Type.Literal(80), Type.Literal(81), Type.Literal(82), Type.Literal(83), Type.Literal(84), Type.Literal(85), Type.Literal(86), Type.Literal(87),
  Type.Literal(88), Type.Literal(89), Type.Literal(90), Type.Literal(91), Type.Literal(92), Type.Literal(93), Type.Literal(94), Type.Literal(95),
  Type.Literal(96), Type.Literal(97), Type.Literal(98), Type.Literal(99), Type.Literal(100), Type.Literal(101), Type.Literal(102), Type.Literal(103),
  Type.Literal(104), Type.Literal(105), Type.Literal(106), Type.Literal(107), Type.Literal(108), Type.Literal(109), Type.Literal(110), Type.Literal(111),
  Type.Literal(112), Type.Literal(113), Type.Literal(114), Type.Literal(115), Type.Literal(116), Type.Literal(117), Type.Literal(118), Type.Literal(119),
  Type.Literal(120), Type.Literal(121), Type.Literal(122), Type.Literal(123), Type.Literal(124), Type.Literal(125), Type.Literal(126), Type.Literal(127), // <- x128
])
```
---

Just ensure that you are on the latest version (0.34.30) and that your tsconfig.json is configured for `strict`. 

Will close out this one as it doesn't appear to be an issue, but if you can provide a repro to break past reasonable limits (128 variants (minimum) is mostly in range of what TypeBox is aiming for) can re-open and investigate. 

> Just keep in mind that some advanced types (Composite especially) may break past inference limits depending on the implementation. There is work being done to improve Composite inference but cannot fix without forcing a minor revision and changing up a bunch of inference infrastructure. Recommendations if you are pushing past limits with Composite() is to swap to a Intersect() type which will give you the same semantic type, but non reduced in the type system.

Cheers!
S

**Comment by Jackson-clipboard** [comment]
Ahh sorry S, 
I missed a line in my copy pasting 🥺 

[https://www.typescriptlang.org/play/?noErrorTruncation=true&ts=5.2.2#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxnAL5wBmUEIcA5AAIDOwAdiQDYHBQD0MdBgBGEAB4MAUDP784AWiXKVqteo2at6qXLgA5COwUARYC2KcYu+drv2HdqUMxwAgnAC8eQsRIAeFwwIKncAPjg9KAwAEwBXEgw4GAg4djiuLikSIwt3LxRhADoAVXZgIwAKAG0pOELMIv0MrkqAShw0RubM9s7intaOhowmlr6Rsd7hrtHBidmpof7u8eG4Osn5mYG1lbm9rcPF7f2lhd3ps9PNk+PL5aOrp8e757fXh4vVq9uvnZ+n0B3wO73+13uwIBoOWfyhELB8JeIPO0NRCKBML6cKxaNOyLxkNxGJR+I+2Pq5MJiOJBJJ1Mx6LpOKZVPp7LpnLZnMi8n8Cjg4gAbAAWFlk8FcyXcmXS8HiomsuVI2Uq5XEhU0pVqnW01V6+WU9Xag26k3miXwzWMy2mu0WxW29HW0mOt1ap2e92wo1mr0e72ugPBn1Sv2BhlBm0RnB6fmCgCMACYABxSAC6bRsikcubz9mzZgsHBI1j0+YrldUzmEcAAQgV8ERSIFhCF6xEorEEkkUnBkym4AA3AhQYAEdjWHLsPIN7yLMoVdg1FkAGWAMAwUAIrQADGj15vt60EweN1ud5Uk2ej5eAMw3i+tEWP4+VACsr8vQq-rQA7B0a7nm+Ka-pUACcYEJvuZyHk+lQJqesHAZeyZQQ+yG3ieL6YfBCaflgQFYQhP64W+CYAWRqGgVRJ6QbRV4wZMcFvkmSHMShrRJteDFJhhRHwUmOEccRSYESJgmkRJrGUdJl6pmBSb0XJrR3kxiwsfeSECW+d48SplR3hhBl3sJGmcYZ4nmcRd5SdZ8F3rJ9m6TRJn0Tpl4iupxSac+7HOZ5+kBc+xnBZUIpmT5FkilZUXESKdlxfBIqUR5z6uWFIrKWF77eY0vkfv5SVvu+QXFZe76heVrTvpF+UWe+BFpR+iX1cR75OdVH4ZV177ZV1Qp5aMBVCkVbXwUKZXjW+QrGbycDxsKYq+sNFmimBQqxdN36tatxFCp122tEKPVHZUQr9Wdf5DUUBV-tpK23RZf5TXt8F-lVV11W9b5-ltP2Xn+u1PcRf6HQD-6nRDlR-u5j0FSmN0I2N0Mpq9IPwSmn2o99GMgf9eOXimwMI6l8MWSmUOE60KaXdD4FIxZ4Eo9TEHowV4HY6z4G4xzTXk8R4Ek0z4Pc1THN06z0GM8R0EswV0HsxZ0H8QLeG7rzyu7gTCu7sLsu7qLuvi1rksK9BUGIYBavkWhDGIVz5ua7L+GW-reEUZbJsu3DBnJjLeFsVB3HB47ytCcHOvh+75FJrJcYCuIA4Zlm2S5PA4ioAAXgUiwAEoYDkUAxJUdZnPgY7sAA5u0bQANxAA](Link to updated code here)

Following you example, this will now show the correct error:

```typescript 

type B = Static<typeof B> // reduce to 128 variant
const B = Type.Union([
  Type.Literal(0), Type.Literal(1), Type.Literal(2), Type.Literal(3), Type.Literal(4), Type.Literal(5), Type.Literal(6), Type.Literal(7),
  Type.Literal(8), Type.Literal(9), Type.Literal(10), Type.Literal(11), Type.Literal(12), Type.Literal(13), Type.Literal(14), Type.Literal(15),
  Type.Literal(16), Type.Literal(17), Type.Literal(18), Type.Literal(19), Type.Literal(20), Type.Literal(21), Type.Literal(22), Type.Literal(23),
  Type.Literal(24), Type.Literal(25), Type.Literal(26), Type.Literal(27), Type.Literal(28), Type.Literal(29), Type.Literal(30), Type.Literal(31),
  Type.Literal(32), Type.Literal(33), Type.Literal(34), Type.Literal(35), Type.Literal(36), Type.Literal(37), Type.Literal(38), Type.Literal(39),
  Type.Literal(40), Type.Literal(41), Type.Literal(42), Type.Literal(43), Type.Literal(44), Type.Literal(45), Type.Literal(46), Type.Literal(47),
  Type.Literal(48), Type.Literal(49), Type.Literal(50), Type.Literal(51), Type.Literal(52), Type.Literal(53), Type.Literal(54), Type.Literal(55),
  Type.Literal(56), Type.Literal(57), Type.Literal(58), Type.Literal(59), Type.Literal(60), Type.Literal(61), Type.Literal(62), Type.Literal(63),  // <- x64
  Type.Literal(64), Type.Literal(65), Type.Literal(66), Type.Literal(67), Type.Literal(68), Type.Literal(69), Type.Literal(70), Type.Literal(71),
  Type.Literal(72), Type.Literal(73), Type.Literal(74), Type.Literal(75), Type.Literal(76), Type.Literal(77), Type.Literal(78), Type.Literal(79),
  Type.Literal(80), Type.Literal(81), Type.Literal(82), Type.Literal(83), Type.Literal(84), Type.Literal(85), Type.Literal(86), Type.Literal(87),
  Type.Literal(88), Type.Literal(89), Type.Literal(90), Type.Literal(91), Type.Literal(92), Type.Literal(93), Type.Literal(94), Type.Literal(95),
  Type.Literal(96), Type.Literal(97), Type.Literal(98), Type.Literal(99), Type.Literal(100), Type.Literal(101), Type.Literal(102), Type.Literal(103),
  Type.Literal(104), Type.Literal(105), Type.Literal(106), Type.Literal(107), Type.Literal(108), Type.Literal(109), Type.Literal(110), Type.Literal(111),
  Type.Literal(112), Type.Literal(113), Type.Literal(114), Type.Literal(115), Type.Literal(116), Type.Literal(117), Type.Literal(118), Type.Literal(119),
  Type.Literal(120), Type.Literal(121), Type.Literal(122), Type.Literal(123), Type.Literal(124), Type.Literal(125), Type.Literal(126), Type.Literal(127), // <- x128
])

const xyz = Type.Record(B, Type.String());

```

Im using version 0.34.25 of typebox, but have also tested with 0.34.30
Im also using Typescript version 5.2.2

**Comment by sinclairzx81** [comment]
@Jackson-clipboard Hiya,

Ah, that looks a bit more like a problem to me. Will re-open.

---

I don't think there is much that can be done about this on the current revision of TypeBox, so will flag for future review. The problem mostly comes down to TypeBox's rather arcane handling of Record Key evaluation where it tests for several Key variants (String, Number, Boolean, Union, TemplateLiteral, Enum, etc). There would be a code path there where TypeBox attempts to determine if the Key is Finite vs Infinite. In the Finite case, TypeBox will transform the Record into a Object with the Finite keys, and it's probably this logic being tripped.

Will re-open and flag for now and try review when I get some time to look into it (currently working across several projects atm), but recommend using the grouped Union it helps prevent the TypeScript traversing too deep.

Thanks for reporting!

**Comment by sinclairzx81** [comment]
@Jackson-clipboard Hiya,

Hey, I had a bit of a deeper look and found a non-optimized (non-tail call recursive) type handling the union key inference (have been looking for these throughout the codebase so it was good you found one!). Have pushed a fix on 0.34.31. 

These non tail call optimized types date back to some of the earlier versions of TypeBox, the culprit was found below.

https://github.com/sinclairzx81/typebox/pull/1209/files#diff-bb1dfc3cfa36bd4b5293a9dd50e4626e22053a008823559a030602b9d5bbea97L109-R118

Things should be fixed on the latest published to NPM. The PR auto closed the issue, but if you run into any problems on 0.34.31, feel free to ping on this thread.
All the best
S

**Comment by sdoshibitgo** [comment]
We are still seeing this issue `Type instantiation is excessively deep and possibly infinite.ts(2589)` on version on 0.34.33.
This is type:
```
type = T.Intersect([
         TypeA, 
         T.Union([
              T.Union([t1, t2,....T50]), 
              T.Union([ty1, ty2,....Ty50])
         ])
])
```

If we use T.Object(T.Any()) it throws the error
