### ISSUE TITLE
`Type.Evaluate` doesn't respect `Type.Base` during `Type.Intersect`

### ISSUE THREAD

**Issue by orimay** [sinclairzx81/typebox#1470]
When I try to intersect a type extended from base and then evaluate it, it turns into `never`

```ts
import { Type, type StaticDecode } from 'typebox';

class TId extends Type.Base<string> {}

const schemaNonEvaluated = Type.Intersect([
  new TId(),
  new TId(),
]);
type TNonEvaluated = StaticDecode<typeof schemaNonEvaluated>;

/**
 *  const schemaNonEvaluated: Type.TIntersect<[TId, TId]>;
 *  type TNonEvaluated = string;
 */

const schemaEvaluated = Type.Evaluate(schemaNonEvaluated);
type TEvaluated = StaticDecode<typeof schemaEvaluated>;

/**
 *  const schemaEvaluated: Type.TNever;
 *  type TEvaluated = never;
 *  
 *  instead of
 *  
 *  const schemaEvaluated: TId;
 *  type TEvaluated = string;
 */
```

Showcase: https://play.vuejs.org/#eNqNlMty2jAUhl9Fo00IQ+1Fu6IOnaZlQRe003gXZaHYB+PEljTSMU6G4d1zJAMxt0w2HnSu3y9+e81/GhOtGuBjnrjMlgaZA2wMq6QqbgRHJ/hEqLI22iJbs/TVwIghPdkdSiyz35DpHNiGLayu2ZXPPOqXq+9CCZVV0jmWznIGLwgqp9+Ujm6lg8ShLVUxYetNqNTK0eZsCbWcazVdyaqRCDm76VpmCsE6yHBwLxRjClo/dnA9Oj49XNPmgJcezenjJr5CL84snATweDikwUPGLnGNO6x0z5XcE8HIYzz4Eb73LEUnO1TEx8JPVO8Cg1OAd5mf0/gZgSfq5rACe6Cmv0z1st2zpFkgc6YX/eilFbP84ujDW0rizpnkQzog1KaiOjolce/AR7xz6ZdamujJaUWeXnt/iG2CrDxmIeJjW6f6mOBLROPGcdy2bdQo81xEma7jbcmPWudNBYL7VrLrhlahI1mLsjhaRF2mrMD+NViS7IOFsqp0+yfE0DYQrBt6lpA9n4k/uS3cPwsO7IoA9jmUtgDs0tO7Ob1eveQO94Pkf3C6ajxjV3bbqJywe3WBdhbujf6K1E39G+x2ojxouI1QLzh9QX59IP0d92v0bX+LmzeR+4iI

**Comment by orimay** [comment]
The most straightforward solution I see is to add `Equals` method to `Base` type and use it within `Narrow` function in `/src/type/engine/evaluate/narrow.ts`

**Comment by sinclairzx81** [comment]
@orimay Hi! Thanks for reporting! (good to see users diving into some of TB's internals!)

> The most straightforward solution I see is to add Equals method to Base type and use it within Narrow function in /src/type/engine/evaluate/narrow.ts

At this stage, the Base types are somewhat at odds with Schema types and I haven't quite figured out how to reconcile them with the rest of the type system. At this stage, evaluating two intersected Base types will result in `never` because TB can't derive structural information from class instances (they are effectively nominal)

But you're on the right track with `Equals` tho! There's actually two functions that need to be implemented (ExtendsLeft, and ExtendsRight) where the extends logic may need to perform the check in reverse. The checks are modelling this aspect of TypeScript.

```typescript
type R = Left extends Right ? true : false 
//
// where: Left/Right is substituted with Base instances
```

The issue tho is that TB needs a symmetric (runtime and type-level) implementation and I haven't figured out an API design that would achieve the type-level check, but I suspect HKT implementations may be required.

---

With regards to API | HKT design, I have been exploring HKT implementations on another (albeit unrelated) project. Where the parser design for mapping AST structures has been working quite well, but where the callbacks "could" be repurposed for dynamic (or type level dynamic) Base type extends checks.

[TypeScript Link | Compilers in the Type System](https://tsplay.dev/N5nqom)

```typescript
type Math = Wat<`(module
  (func private_function (param $x f32) (param $y f32) (result f32) (result f32)
    local.get $x
    local.get $y
  )
  (func (export swap) (param $x f32) (param $y f32) (result f32) (result f32)
    local.get $y
    local.get $x
  )
  (func (export add) (param $x f32) (param $y f32) (result f32)
    local.get $x
    local.get $y
    f32.add
  )
  (func (export sub) (param $x f32) (param $y f32) (result f32)
    local.get $x
    local.get $y
    f32.sub
  )
  (func (export mul) (param $x f32) (param $y f32) (result f32)
    local.get $x
    local.get $y
    f32.mul
  )
  (func (export div) (param $x f32) (param $y f32) (result f32)
    local.get $x
    local.get $y
    f32.div
  )
)`>
```
 
---

Unfortunately, there's no established patterns for handling these kinds of things in the type system (this is on the upper end complex design work, so progress here will be slow). There won't be any significant changes to the TB type system before the end of the year (just stabilization work mostly) so will pick this one up next year .... but experimentation from the community is always welcome! Design suggestions too!

I will drop a research tag on it for now. 
Cheers!
S

**Comment by orimay** [comment]
@sinclairzx81 it turned out it was easier to fix. Now it will work

**Comment by orimay** [comment]
@sinclairzx81, just FYI, this is not a breaking change (unless someone relies on getting `TNever` for `Base`, but I don't think it's very much probable and/or limiting. `Equals` method is not required and has a default implementation, and, most likely, is only needed for generic variants (as shown in tests with `Bar` class). Would highly appreciate it if you get some time to merge it, as it will make my complex project much easier. Please let me know if any other adjustments are needed. Thank you!

**Comment by sinclairzx81** [comment]
@orimay Hi, thanks for the PR and sorry for the delay (have been busy wrapping up work for the year)

---

So have had a look through the PR tonight (thanks for this), but not too sure about the current interpretation of Base. The implementation provided performs a structural Equal comparison check on the Base type itself (which gets around Never), but I'm not sure if it's accurate to perform the Equal check on the Base type instances themselves... but rather the structure Base is trying to represent .... 

## Base Represents Structural Types

This is a more concrete example of what Base Extends would need to model for [Reference Link](https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgehrgFonmXW32POuvb6AKAIwBKREQDKAYyjAwMAFxwxMKAFcJMFVACGAGzgBRMjFQA7ACYBnXo26279+5QDelOHEJo4ANVTroAZjgAXjgnODIFExUQYlQoABo4JEjo2IS4AC8UmLi4AF9XdyJvXxhoACZg0PDstMTkuCicqHzqNw90AEEqnz8oQNQjU0sSvsqAfndVdAUMXQt0OimVVEKOuAAhHtKKuEHjcwtRsv64SeUVuFn5xfo5nQXKAqWHV7e36z5ykWQ0DfIFEpVOpNLoDENDtZ3tCYRxnIUJBATBZ4GFOoktnkqr9UAA6STSWR8AAGhXaxV6J0CITCEUaqTi9VqjMyzJaBTc5M8lN2NJq9OaTIFaVaZKKnm6IR5p32wyO0omyxmmBucDF6y2Up2UEqssOxwCZyVVxVD3QhWJQjWxUlojQ+JgWhgwAkAB4OhAMHBOgA+OBLC6rLnoTV2vFKJ0u91ET2bP1Le6PZ70WGp1Offw-Ij-OkbLQLcEHEZ5x50awbVA6CAAdwNpy05jrurIYCgqAsRy0cBRwI02j0FgAFlo0IliCp4IOa2qlkOICodGZ3IP0DjcSXUK7cdu-WZ21JgLE4AAZVAYeD0ABKwAA5oP4PmLLeTFpiMAdMBCJNeFC03+Pi4bgSDoj51gMEIjGuG6urSbJCk0dSssKuR5H6YQ0AAVGc4yTBh9AcnAwGgQqewQUcUH5pusHIekDQIShfqckxTHoVhOG4fhbSEUiKLetiRC4oYRYWHwTh5IkJioLWCoSVJYEiEsgxoOoCgIEJcoINMCI8fAoZruphyieJjRydK-iydJ2rfP69BKaUqkGZYABiNxPL+-4ebYnwACxZn8AKbJRhZyooEgriAkYSO5nkxew8JASBHZgaRwlhuulEwfy9G0XBSHZfkaH+mxOFwHhrRATpTb8faBIyDAJLUdl8EMuylpcYiyLwLa+lkUZiQySZll9JmNmkcp8iII5FiaSs2mdZs1V4lNfWDWB-VWQptktvZk1kS5ZpuUAA). The goal would be to have Base behave the same as schematic based types, but where the mechanisms to achieve this are not clear (as of writing)

```typescript
import Type from 'typebox'

// -----------------------------------------------------------------
// (1) TypeScript: Structural Extends
// -----------------------------------------------------------------
{
  type Vector3 = { x: number, y: number, z: number }
  type Vector2 = { x: number, y: number }

  type A = Vector3 extends Vector2 ? true : false // true
  type B = Vector2 extends Vector3 ? true : false // false
}
// -----------------------------------------------------------------
// (2) TypeBox: Structural Extends
// -----------------------------------------------------------------
{
  const { A, B } = Type.Script(`
    type Vector3 = { x: number, y: number, z: number }
    type Vector2 = { x: number, y: number }

    type A = Vector3 extends Vector2 ? true : false 
    type B = Vector2 extends Vector3 ? true : false 
  `)
  type A = Type.Static<typeof A> // true
  type B = Type.Static<typeof B> // false
}
// -----------------------------------------------------------------
// (3) TypeBox: Base Extends Base
//
// Below Vector3 and Vector2 express a structural shape, but how 
// should the Type.Base<...> describe Left / Right assignability? 
//
// -----------------------------------------------------------------
{
  class Vector3 extends Type.Base<{ x: number, y: number, z: number }> { /* ??? */ }
  class Vector2 extends Type.Base<{ x: number, y: number }>            { /* ??? */ }

  const A = Type.Extends({}, new Vector2, new Vector3) // expect: TExtendsTrue
  const B = Type.Extends({}, new Vector3, new Vector2) // expect: TExtendsFalse
}
// -----------------------------------------------------------------
// (4) TypeBox: Base Extends Schematic
// -----------------------------------------------------------------
{
  class Vector3 extends Type.Base<{ x: number, y: number, z: number }> { /* ??? */ }
  const Vector2 = Type.Script(`{ x: number, y: number }`)

  const A = Type.Extends({}, Vector2, new Vector3) // expect: TExtendsTrue
  const B = Type.Extends({}, new Vector3, Vector2) // expect: TExtendsFalse
}

```
So in cases (3) and (4), we wouldn't perform a check against the `class Vector3` or `class Vector2` instances, but rather the generic parameter `{ x: number, y: number, ... }` as this is what Base is structurally representing. The Base type should provide a mechanism to allow it to perform cases (3) and (4) but where there is no obvious mechanism to achieve this. 

> Note: The closest thing I have to derive a structural type / schema from TS type is [ReverseStatic](https://github.com/sinclairzx81/typebox/blob/main/example/prototype/reverse-static.ts#L116) but only solves half the problem (there is still a runtime mapping aspect to this). This needs a lot of work.

--- 

## Equal

Looking at the current Equals check, I'm not too sure this would work quite right without nominal typing support in TS. For example, the following Base types are structurally Equal.

Ref: Nominal Typing in TypeScript (from 2014) https://github.com/Microsoft/TypeScript/issues/202
Ref: Nominal Emulation using Structural LR Checks [Reference Code](https://github.com/sinclairzx81/typebox/pull/1480/files#diff-5d55bd09c3522e77908615d62301522063e2ff5e80ffc0f35f22c3ce0bc846bcR51-R59)

```typescript
// These instances would be considered structurally Equal
class A extends Type.Base  {}
class B extends Type.Base  {}
```

This said, there could be some utility in performing instance level extends checks (as per PR) but this would be somewhat orthogonal to the generic parameter structural requirement for Base itself. It is worth considering tho.

---

### ExtendsLeft / ExtendsRight

I do think there needs to be a ExtendsLeft(...) and ExtendsRight(...) override for Base, and where the Left / Right implementation would need to try and derive associativity corresponding to the Base generic type `<T>`, but it's not clear how to achieve this, or what the API for such a thing would look like (HKT's spring to mind, perhaps calling to [ReverseStatic](https://github.com/sinclairzx81/typebox/blob/main/example/prototype/reverse-static.ts#L116) or user defined implementation)

... but given the challenges, the current implementation is basically saying ....

 > "We can't see into the Base structure, so we can't accurately tell if Left extends Right  (or vice versa), so the safest thing is to say neither type extends, even if Left and Right are the same instance of Base"

The default of `Never` is somewhat unfortunate, but is a stand-in until the structural representational aspects of Base can be resolved (it's a really difficult design problem!!!)

---

Unfortunately, I don't think I can take on the PR as it's only solving instance level Equals comparison on Base, but still happy to discuss more. 

Like most things in TypeBox, these kinds of designs tend to move at glacial speeds and there needs to be a lot of experimentation and design work done first. If I get a implementation wrong, it usually means I need to carry the implementation around for years (and there is some uncertainty if Base will be a long term type in the library given the reconciling challenges with structural types)

But lets discuss more.
Cheers!
S

**Comment by orimay** [comment]
@sinclairzx81, thank you for the detailed response! I can see an easier option that may make everyone's lives much easier. What if `Base` constructor accepted an optional schema of type `T extends ReverseStatic<Value>`? Then we could have used that type for such checks and type merges. And some types, like `Date`, could have had that omitted:
```ts
class Vector3 extends Type.Base<{ x: number, y: number, z: number }> {
  public constructor() {
    super(Type.Object({
      x: Type.Number(),
      y: Type.Number(),
      z: Type.Number(),
    }));
  }
}
```

**Comment by orimay** [comment]
Also, it's not a breaking change and is a progressive enhancement

**Comment by sinclairzx81** [comment]
@orimay Hiya, again, sorry for the delay.

> thank you for the detailed response! I can see an easier option that may make everyone's lives much easier. What if Base constructor accepted an optional schema of type T extends ReverseStatic<Value>? Then we could have used that type for such checks and type merges. And some types, like Date, could have had that omitted:

> Also, it's not a breaking change and is a progressive enhancement

Hmmm, perhaps. I have been mulling over this issue, and the more I look at the Base type, the more I think the introduction of it in V1 was a mistake. TypeBox really wants to operate in a structural sense, and the requirement to add additional "things" to Base to make it integrate correctly seems to be an indication the type is not fitting the TBV1 design (at least not in the way I had hoped I could get it to work)

Let's consider that ReverseStatic + interior Schema suggestion, and just to follow through on a train a thought.

## Base

This could technically work where `ReverseStatic<T>` could be used to constrain the Base constructor (super)

```typescript
class Vector3 extends Type.Base<{ x: number, y: number, z: number }> {
  public constructor() {
    super(Type.Object({
      x: Type.Number(),
      y: Type.Number(),
      z: Type.Number(),
    }));
  }
}
```
... but the natural extension of this would be the following....

```typescript
class DateType extends Type.Base<Date> {
  public constructor() {
    super(Type.Object({
      toString: Type.Function([], Type.String()),
      getTime: Type.Function([], Type.Number()),
      toISOString: Type.Function([], Type.String()),
      toUTCString: Type.Function([], Type.String()),
      // ...
    }));
  }
}
```
... which just makes me wonder if just this would be reasonable ...

```typescript
const DateType = Type.Object({
  toString: Type.Function([], Type.String()),
  getTime: Type.Function([], Type.Number()),
  toISOString: Type.Function([], Type.String()),
  toUTCString: Type.Function([], Type.String()),
  // ...
})
```

... because it naturally integrates with the TB type system with no additional complexity [Reference Link](https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgYwgDsBneAEQEMZVk04BeRIgDoA8sQBWqGjAAUAb0pw4MCAGUYUYPQDmALgFpBAMQCu9KcAbSA2gF0ANPtSC1G7dICU7uwrhbUMBFBUPW4nEzMYC3pre0dBADljEGJUKA8vH2UASRVhF01dOPDzS1sHUOd1AvTvRWUAVQQAYXztEKFiyNLYitatGp8AekG4QTHKAF93amG4AFEANzYAG2MOKLgAdWgAa0Y4AB84LPpOKEZJTgATOCaoVA5UG4AFbDRYJGo6Jng506gkHw4osVmtONIKiczhcpNZFLNvsx5v8kO0DAhRBIpAAeeSKCqYy5yOA0e6PK56dicUJwKYORQMxmzRSkh7XNFODHiS64nwE7mw2QksnsuBUrhEWleRkyuDMhnKPocwQITpRbFlOIIPoAPgA3JQbJ5ZSbTWbzUyRoy-AEgsrVaYSvQNT0hAhEslUvqfBbfX6zfK6hAcnkqm0tWqGC7ym7dQb-QnE-CrQqII0WmHChUHRF1Zrs3GfUniwGUxNvSXK6bZuXqBhHV16EpUMxpKgUcq1OsaNjCGgIBhkeokDr3HA8SyGEjgIwIED28PBKzyYJsrk+h4ZbM2GA0GxznBlsAdug2L5lhBiCsEAALGeCcWTIA)

```typescript
import Type from 'typebox'

const DateType = Type.Object({
  toString: Type.Function([], Type.String()),
  getTime: Type.Function([], Type.Number()),
  toISOString: Type.Function([], Type.String()),
  toUTCString: Type.Function([], Type.String()),
  // ...
})

// Evaluation Works | Intersected Property

const Entry = Type.Evaluate(Type.Intersect([  // const Entry: Type.TObject<{
  Type.Object({ created: DateType }),          //   created: Type.TObject<{
  Type.Object({ created: DateType }),          //     toString: Type.TFunction<[], Type.TString>;
]))                                            //     getTime: Type.TFunction<[], Type.TNumber>;
                                               //     toISOString: Type.TFunction<[], Type.TString>;
                                               //     toUTCString: Type.TFunction<[], Type.TString>;
                                               //   }>;
                                               // }>

function test(entry: Type.Static<typeof Entry>) {
   const iso = entry.created.toISOString()     // appears like a globalThis.Date
}
```

---

The above would be the natural way to express arbitrary structures using the TB V1 type system .... and much of the ground work has been setup to move the library in this direction. I guess the main issue with Base is it requires bolting on all this intrinsic functionality (Check, Clone, Clean, Default, etc) just to be able to compensate for the fact it isn't a schematic,. My general thinking is that the additional complexity to support Extends / Evaluate probably indicates the Base type is probably the wrong fit.

What are your thoughts on this latter example?

---

Again, sorry for the delay (busy end to the year), but still very keen to discuss this further. I'd like to get some thoughts on this latter approach as it would be technically feasible to validate for Date (or other) instances using structural checks (while also letting types naturally evaluate under the TBV1 type system)

It's a bit of tangent from Base (we can return to this), but would be keen to hear your thoughts on the above all the same.
S

**Comment by sinclairzx81** [comment]
@orimay Hi, just a quick additional update here.

I have just pushed a small update on 1.0.64 to enables the following.

```typescript
const Uint8ArrayType = Type.Object({
  BYTES_PER_ELEMENT: Type.Literal(1),
  byteLength: Type.Number(),
  byteOffset: Type.Number(),
  // ... additional
})

const DateType = Type.Object({
  getTime: Type.Function([], Type.Number()),
  toDateString: Type.Function([], Type.String()),
  toISOString: Type.Function([], Type.String()),
  // ... additional
})

console.log('Uint8Array', Value.Check(Uint8ArrayType, new Uint8Array())) // true
console.log('Date', Value.Check(DateType, new Date())) // true
```

.. and for TId

```typescript
import { ObjectId } from 'npm:mongodb' // ???

const TId = Type.Object({
  _bsontype: Type.Literal('ObjectId'),
  getTimestamp: Type.Function([], Type.Unknown()),
  toHexString: Type.Function([], Type.Unknown()),
  // ... additional
})

console.log('TId', Value.Check(TId, new ObjectId())) // true
```

... In the case of Date, it would be possible wrap the schema in Unsafe to infer as a `globalThis.Date` [Reference Link](https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgYwgDsBneAEQEMZVk04BeRIgDoAqkzYZUAHgDmAGwjE2shAAtgjQe04A+ABTdUggPLEAVqhoxdAb0pw401DAShUALgFpBAMQCu9S2AGXQBtAF0AGk9DADlfEGJUKF0AShSIuzgYCC1UAGUYKGB6aQ8DH39A4PCo8oKiktT0zOyASTyjeuLS6IqAmCD6UMjersa0jPsAeim4QXm4NgATJeABhiVKAF806kIeBD5RmA5gGkl91AgMOFyDbTgZrKJEI9ygA)

```typescript
import Type from 'typebox'

const DateType = Type.Unsafe<globalThis.Date>(Type.Object({
  getTime: Type.Function([], Type.Number()),
  toDateString: Type.Function([], Type.String()),
  toISOString: Type.Function([], Type.String()),
  // ... additional
}))

type T = Type.Static<typeof DateType> // type T = Date
```

---

Again, open to thoughts here. The function checks are not perfectly ideal as it's not possible to derive parameter and return type information from JavaScript functions (the best TB can do tell a function exists at a instance `key`), but this approach does achieve some level of structural duck typing which would naturally integrate with the V1 Extends and Evaluate infrastructure.

This is worth some consideration as an alternative to Base.

**Comment by sinclairzx81** [comment]
One more reference link for consideration [Reference Link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgehrgGUBjbAG1bgBlgA7dARgBsAJkzQ4AVQDOAQwDmqarXoBaNeo2at2nbr36tyuITRwAJqijAAbqjOZsuVsGIA6M65hSjB33-8BapSoZJCwcEwQPFLwACIyMKjIpgC8cAAUAJRwKQB8iESuAPLEAFaoTDDpAN6UcHAA2gxIIKSsnhAAClYgwDA2qAC6AFwFaK4AgjxIWQA0dXA0AFRLcABKqDAArlDRcDJwMVY8cnBQqGDnUqg8MAnAUXAQGPvmCaiuiAAW6BjQIAkni8YD9DjBjqcLGgeGYpE8eMZQawIEwZKwPnAljQFjAIAxwbw5KNkh8AGJbHiVB48dINQazMYffEQrKZeb1ZarDbbXZwg5md77PlgiFwaxorYYrE4iDxRLMwnEwrkyn9KK0+mM1wKk6s9mLFbrTY7PYHfogdAyYVHQliiVS7H1XEIUCoHVErUqqnqukMknagm6zJshaco080121iSoWvG0nKMxmRgS4QS7AQW4xHoL4QGJwG7WYDYHgW254OFMHbnW5wZGo9GfaVOiCcFFot2Bj3+r1qmm+rXuvWhw3ck3CgWJWMHeOncXRy0p7DpzMQbNwXP5wvFqJlmAViLVm7wesdpuO4yt9vouWdiFK8a96kav2FIfB-Vhse817my3WrtE0XVMVynLMQRzPN4G3Es9wPKsoBrE9rwdGU2wbJJXXdB8yQpb1+01f13xDDlR2NH8ILBaA7GMV0gLgXg4F6dhgGuSIYThKReCYdBejMHhgDkL4YAZAApGQeC2GQoCQOB+AZfgAE4AHYAAZJAQABhc8FnnSUigwHDXCfH1CMKAA5LZWksYdSK5ci9komJqPsP96MY5jnDYqJYUObjeOAfjBOEsSJKkmS5IUlT1IkLSdPqBQYBdC0jJMgjX3GSzrKgWyDVWABxTY4UopBUGkhkti4hNTw4P94rgRLyXYABNMqoFSvC+xfLUsuIGyPxHAqivXUrpLgSrbQkATbCgWQOE0iBoDMXh3nsZL0HSWLNMyerEq2prWFa6SOtVZ8B39Xr+pIvK4EKrx1xAKIQQqqrThq2iLV2zYAFknq+E78O6i6rL6nKBrs27hsox7bi+IFXlvJ4ygqeAJoTKaBlmtE4AWpaVsSNa6M2rSdsxC89q037YYBrrzoskGrs-Q07uK0EBSQFRnhUCCVBh57xteutrw+1CEs2W8abOszMoZsHrrDFn13ZzmMG5n5eb+l7Jumyw5pxxaoGWnhVsQImttJ5sGs2LaJc9TqpYyj5Lrlpmhvuyj2fhyiAHdUFQABrLXquFuqyYWRL4iQSXTMd1xndyhWobZmRZOeddfYDgXtcxvXccN-GaPWjJza+mAbZT6P0p62WE+ZpPIJ2OFGP5d4g7ekPXVLgAJCBG8roH6ey2u3dZhvZvchEDkRiBkcqLP0Z1rH5oNo2TaL4nttLrae77u3Tpj6uh-Bm7Feh3gtkSOE06nwUZ-KSo26FhsRdL77z8v-u6Zlo-5br93QV6JJS+8Mb5TjvijeepwMYzVzivAuhMLTFxJlvSm79UBSE-tLJ2Ndj6J3-ugbyHEQFwGnrPESkCn7Y1DpbRKDAKg+QwXvQGX9sE-1dpDfBhx6FEOviQ2+ZCKHQN1tjPOq8Cam0QRvC25NrZaToexWEmDY7x1wX-UeTFgAsUIb5Xht5H7vWoTImAb8tHcMUUw2mWC444N-iPB6mivJmKvi8UB6BwFzzRlAxesC8bG3EevEuYcxZl1QaYhRjCez2wPsDNhg0OHqOWhgDAlgbg8QYgiQBF90FwD6jADOCIhFL31r4teZsSb7BhOuNyjxKLvUiOALJUBS7rQAF5RFQAZDA1wYBKMPqDYeCxMSMHrm8KcElXJ0T0ugRilFSH3xgK4QZqwAACYBpIyFwG5CYcBJIWisEwei5xLjoOPLaSiuzQbw1QKwZM1x7CeVYk4vylIApBSEuQ8SklpKyXknJaKt1voIEWfUIJXCkquk-jE-pmQrEqNsUs4ZnCHnaLhFM9J645kQM8ZQ2qncEWrPWbgEAcJtm7MsMAA5aLUAAEcpK1TXGfMJPkgLAvqJbbpJjHHhMhYPaFsKbGuwRXQpFDjHnhInhi-h8zBHeJEXAvxhcymb3xWsqAGymIkp2VZcllL7QFlpVQhlADRXaJZUsi83StqcrFQwnl38+XKIFYNIVIyUUStmVKrFgsDF4pBSs1V6q2JwFJdq-Z9EaV0svOuN1UzWVDIJWqolmqyVhqpQa+l9imVENjeahY3T5G2osWdKF-VY5FDAH2NE6QS1y35bEuyLrOExr1TM0EmKPGC0KT4-OCqEEbRLiqwlXCDkhr2RS8N6ao1OSeTmv1cAE3quJcGrVY7dULn1ZG8Cxqs2+VnWyi1sjNIFo4na1h0Ky0VupFWmtrI63QvhXO4V6jMnALRa29A7bUbeo7p9QdiaNEIlHTqidm6jUBSAdkvd8aA24CDUB1NeqI2GujTO+0cb-VDqXfB8dabQOZq5Qws1fqD3GLQRE5UUT+w3rZFqctlbWDVt5YzWjl6ojXqY7Wx19a8qNufWR91bbPUduzjAuVJT-FKp2n+xdjFsNrpjEhjNZ8IOorQ9J2DFRl0ppw4hydW6CGoYXOh+dMGNVadDTp9dimp3boI9mtTxG82Hrfip091ij4Xvo4x+1zH-R0avQx6jMKuP3sFY+kZuYdgCY-UJr9tofW-rnQu3AkXx5yZA8hyiqXVNGfUwB8zq6MtKeNSpojbKTNDrgyu4DuHMugmbblpLpmsPVYQ1ZvTYGNE7py5KdDJGd6zTcyozzAXvNnt84UfzbHAscb1CxrzQW72M2deFzh2Xot8LAQI7FXaxM9tKZIgdTWh3rfS7V4rY8esfDy4AgrNXdN4eU1kq7xnkvDru21hTHWUPiqgxh-9LXtPyfQNZ-TXW7O7oc-upzITNIDfI4+SjtJqMjem2N9zoX5ujaC6j42M2fOcb6cthtq31FA7eBzLmPM+ZwzRWnD1W3pXYoS9d47-7JzoDOw9ur6BPb04AX9PrMPbaRP3lR2bwWicuxW+Vp965yd8+BAL2G6KGduO2522Vy9xOKsO8gvLHOPuWa+495Oqcle8UF7m+olqtIi4o2L5HEulvS5J7LkZNONufooSz17zW-pG+BxunnTFBffHQGiv4UA4CfPCrJVicBVIMnGU8CC0fPdTLhH8dgEBvYRCiGxC+AxWBID90Ow3XP11HKuKchMHsU5e2VyCT4ABJJXCe31wh4BAeAUgtgpmcHYBklFI+OFeA2C7VsYCIwtCCCA9gE+VTsELm3P0-pDZwbj9jBPb0heJzx0nD0A9voRGrpGTPNc5z22I3X-b9ds8XQHyvJuQ808+AgUEkfxCx++QxOESeKl7Ae8fh09j97Qs8IAc8892JC9+hbAS8y92dBRn90Bq8TlbgzkzdG9LdYZW8Xg+g-8dke9Dh+8wBB8zBh9P89UsAcBx80RJ8KZNIZ9NhcwF84Ql8PBrcwUrV18i0fQUcsc0dFs99XcD93dOFRpo9+cYtGcvV4sf1Wdys3tJDA96Io8Ro2pEDH8VdtkWlLAIAVBiArQaJycv9o9oYA90h1J1Cf8ZIFJ+AxBo9YgKhUBspSZvpKp4A+pDg0AmBgAMBgAaJ-CV1EYE8pBfD-DAjOCH9cAK9WtjcQdJ11D69zcj9cCuDukDojp2o+Dxcd8aM-NWM8d0c4Ut98dxtCcccZchk5cSo2ovdYsZUr9td9sJM9dlUYi4AVCUDg9J9JCtCiUn94ig9QdOs39w81Dv8wpf8E8ACU9gDLBQ8VdM8xAoD89ogKgi94DS84APD8xvC+8B8oiGIXhdlQjOJSDyCBjRlOdhiisbNecG9pCljm8MjD0si2oN8PNBDiiccfjt8Kjd8pdh5wxxxXhDd2IZpxEswZxAIdstdilWjb8kFN5QVcQtpsJciB5xhiJ2FvxIxDcrQ4xAIT84AW8GAihHCAQFk0SIBySihMTRdmErFcS4lpAaJiBZJKJRIKTzJXBZx-DZJZ9WCo0bgZBiB0Qqk1Vogo9qTqQQEER3F9w4RJwDgbCZBxRmArAK04AShpVzIe97hHh0geSihzJshrgrA0RgAWkjSeB6pcRTTzI3Mptfi3wuwgSiIPSBpQx6AZAzBlp6Nw5NgAA1aSe3RHR3FhSYaYVkSgAAX0yGoDoDgECDTPTO0CMGkHkFQGJHQXgGZC2EqB2GxgAFFaUbAOwXkfAMzaz0zKAYC4hBQ0hbwSQshqAMBKN9gmAeIK18pkQjDWBbx0gplRg5ABy0QP9WJXBbxshah6hY0I53h2z4zKBOyxduzeyYB8R7gmBhzRzBw7h+gmAAAeEwVANOW8XIOc3SNDJcxIds+oGQHsi4GAfsmeNEfc+0JM1cygZ8rcnc484cvgPPccj81gKcqQGc5c4MIAA)


```typescript
// ------------------------------------------------------------------------
// type derived from lib.d.ts
// ------------------------------------------------------------------------
export const DateType = () => Type.Object({
  [Symbol.toPrimitive]: Type.Any(),
  /** Returns a string representation of a date. The format of the string depends on the locale. */
  toString: Type.Function([], Type.String()),
  /** Returns a date as a string value. */
  toDateString: Type.Function([], Type.String()),
  /** Returns a time as a string value. */
  toTimeString: Type.Function([], Type.String()),
  /** Returns a value as a string value appropriate to the host environment's current locale. */
  toLocaleString: Type.Function([], Type.String()),
  /** Returns a date as a string value appropriate to the host environment's current locale. */
  toLocaleDateString: Type.Function([], Type.String()),
  /** Returns a time as a string value appropriate to the host environment's current locale. */
  toLocaleTimeString: Type.Function([], Type.String()),
  /** Returns the stored time value in milliseconds since midnight, January 1, 1970 UTC. */
  valueOf: Type.Function([], Type.Number()),
  /** Returns the stored time value in milliseconds since midnight, January 1, 1970 UTC. */
  getTime: Type.Function([], Type.Number()),
  /** Gets the year, using local time. */
  getFullYear: Type.Function([], Type.Number()),
  /** Gets the year using Universal Coordinated Time (UTC). */
  getUTCFullYear: Type.Function([], Type.Number()),
  /** Gets the month, using local time. */
  getMonth: Type.Function([], Type.Number()),
  /** Gets the month of a Date object using Universal Coordinated Time (UTC). */
  getUTCMonth: Type.Function([], Type.Number()),
  /** Gets the day-of-the-month, using local time. */
  getDate: Type.Function([], Type.Number()),
  // ...
})
```

**Comment by orimay** [comment]
@sinclairzx81, sorry for late response as well, things are busy here. I was hoping to not express `Date` as a set of its functions (or any other class, especially imported, that may change over time). My use cases include, for instance, [RecordId](https://surrealdb.com/docs/sdk/javascript/data-types#recordid) that I get from the database, and I convert it to a [branded type](https://www.typescriptlang.org/play/?#code/CYUwxgNghgTiAEYD2A7AzgF3gfWwIxihWAC54BXFASwEdyE0BPAWzyQgCgNGAHBAIULEAPPwB88ALzwA3vADauAkWABdMv3gBfDhxAAPHkhhZufeIJUhgwgCoAaCxOm34AMgtCb43V14IAVTQQGABJABEpTysbTBgqFABzRwAiIJDQ4BSxP3MABSRMCKjLYmthOITk+BSCoqycswQAYSRmZhAUDGLpUtBYjHik1Nb2zu6G3MDgmCiZDnh4KlJ4dLDwgG4F+BQoDrJKpI4dKfg6rGl5xeWyc4itxaQAdxQMlcPEh8Q2jq60MlGvwwaHkqmOuia8EB4zQc22NyhP3GEW2GCoHUwex4B0GVW2bGAjBxQ0S2yg5AwAAtjJkyGsUScoEwUGB4AAzShgNGoeCJEAYaF-ABixnOAAojPVboVuuFHOSqTSVvTwgBKWTbAD0mvZ-LAlPgaDaCGAUAwUHByHQWHIMzmWngTNWdo4Vsw8ElF1kDqd51dqHdyDGfyifIFSOFoplYttIQAdMt7J6E8B1dr4IAZcngtkpVFhbKgVAgsLQCTACAABrGYCmK0tYUg2fBISrHcQdkgzjLik6DHwudYgA). I tried dealing with `Type.Unsafe`, but it was not a very pleasant experience so far. `Base` type seems to work well with cases like `RecordId`, because the check is not based on a set of properties, but rather on the simple `instanceof` check, and the same perfectly works for `Date`, or any [Temporal](https://tc39.es/proposal-temporal/docs/) type, that I use. Most likely, my codebase will be out of reach for until after the 4th of January, but my project involves some complex type transformations, and that's exactly why I report so many issues `:D`
- I load a structure from [SurrealDB](https://surrealdb.com/), and it has some classes, such as `RecordId` mentioned above
- I transform it into plain data that I can work with (e.g. I transform `RecordId` into a branded `string`, and some `string` to `Temporal` `Date`/`Time`/`DateTime` instances)
- I store it inside a class, that allows reactive access to the data properties via [Vue](https://vuejs.org/) and tracking of the properties that change deep. I use yet another class, that converts between plain data and the class, because my reactivity-tracking class uses TypeBox schema, so it can't be a part of `Type.Codec`, as it would cause self-reference `:c`
- Once the data gets changed, I encode everything back into SurrealDB representation (where I use `RecordId` in place of the branded `string` and `string` in place of `Temporal` instances again) and send it to the DB.

**Comment by orimay** [comment]
Hello @sinclairzx81! I hope the 2026 brings you lots of joy and success :)
I wanted to point out that my primary pain point is the ability to express classes via TypeBox. While I can go over all of their properties (and rely on duck typing), I can not  rely on this, as classes may change over time. Relying on `instanceof` checks is much more reliable. `Type.Base` really helps here, and if you remove it with no proper replacement, it's gonna hurt a lot. I get it that having a generic version of this type may be a little out of the design of TypeBox, but classes seem like an edge case, that needs to be handled correspondingly. After all, when I feed the output of TypeBox to SurrealDB, that expects a `RecordId` instance, it won't accept a shape of
```ts
const schemaRecordId = Type.Object({
  table: Type.String(),
  id: Type.String(),
});
```
Of course, it's possible to use `Type.Unsafe`, but it looks like a much worse alternative to me (especially if it's not checked). It's pretty much like using `any`

**Comment by orimay** [comment]
Hello @sinclairzx81! I hope things go well.

Just noticed the latest release deprecating `Type.Base`. Just wanted to let you know that we still have this issue unresolved:

> When I try to intersect a type extended from base and then evaluate it, it turns into `never`
> 
> import { Type, type StaticDecode } from 'typebox';
> 
> class TId extends Type.Base<string> {}
> 
> const schemaNonEvaluated = Type.Intersect([
>   new TId(),
>   new TId(),
> ]);
> type TNonEvaluated = StaticDecode<typeof schemaNonEvaluated>;
> 
> /**
>  *  const schemaNonEvaluated: Type.TIntersect<[TId, TId]>;
>  *  type TNonEvaluated = string;
>  */
> 
> const schemaEvaluated = Type.Evaluate(schemaNonEvaluated);
> type TEvaluated = StaticDecode<typeof schemaEvaluated>;
> 
> /**
>  *  const schemaEvaluated: Type.TNever;
>  *  type TEvaluated = never;
>  *  
>  *  instead of
>  *  
>  *  const schemaEvaluated: TId;
>  *  type TEvaluated = string;
>  */
> Showcase: https://play.vuejs.org/#eNqNlMty2jAUhl9Fo00IQ+1Fu6IOnaZlQRe003gXZaHYB+PEljTSMU6G4d1zJAMxt0w2HnSu3y9+e81/GhOtGuBjnrjMlgaZA2wMq6QqbgRHJ/hEqLI22iJbs/TVwIghPdkdSiyz35DpHNiGLayu2ZXPPOqXq+9CCZVV0jmWznIGLwgqp9+Ujm6lg8ShLVUxYetNqNTK0eZsCbWcazVdyaqRCDm76VpmCsE6yHBwLxRjClo/dnA9Oj49XNPmgJcezenjJr5CL84snATweDikwUPGLnGNO6x0z5XcE8HIYzz4Eb73LEUnO1TEx8JPVO8Cg1OAd5mf0/gZgSfq5rACe6Cmv0z1st2zpFkgc6YX/eilFbP84ujDW0rizpnkQzog1KaiOjolce/AR7xz6ZdamujJaUWeXnt/iG2CrDxmIeJjW6f6mOBLROPGcdy2bdQo81xEma7jbcmPWudNBYL7VrLrhlahI1mLsjhaRF2mrMD+NViS7IOFsqp0+yfE0DYQrBt6lpA9n4k/uS3cPwsO7IoA9jmUtgDs0tO7Ob1eveQO94Pkf3C6ajxjV3bbqJywe3WBdhbujf6K1E39G+x2ojxouI1QLzh9QX59IP0d92v0bX+LmzeR+4iI

The code with `Type.Refine` and `Type.Unsafe` suffers from the exact same thing:

```typescript
import Type, { StaticDecode } from 'typebox'

const TId = Type.Refine(Type.Unsafe<string>({}), value => typeof value === 'string')

const schemaNonEvaluated = Type.Intersect([
  TId,
  TId,
]);
type TNonEvaluated = StaticDecode<typeof schemaNonEvaluated>;

/**
 *  const schemaNonEvaluated: Type.TIntersect<[TId, TId]>;
 *  type TNonEvaluated = string;
 */

const schemaEvaluated = Type.Evaluate(schemaNonEvaluated);
type TEvaluated = StaticDecode<typeof schemaEvaluated>;

/**
 *  const schemaEvaluated: Type.TNever;
 *  type TEvaluated = never;
 *  
 *  instead of
 *  
 *  const schemaEvaluated: Type.TRefine<Type.TUnsafe<string>>;
 *  type TEvaluated = string;
 */
```

Here's a new showcase:
https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKYBo4G84GUYCGMwAxgCKokQAmqcAvnAGZQQhwDkMKqARhAA8OAKGFUAdgGd4CAJLU4AXkQ8AdACVUTYONQAKZGlUBVKQSaoAPNKg6A5gD49WegEpMANwIAbAK51FBzhuNAgmOC8-AMVlDht7DldRCWk4SRIAC1QQAgA5CHEAUUjfIlQFZUNUVVlxGFQoSUoYPQBtYThEeXQOruoegF1XAG5hELoEfKKSsoq8QmJyShorcbC0zOy8guKfUvrqB1HhAHoAKjOOs86U+HSsnKndv1mALhUjOTqGppIYS1acn6fQGRyunXGiCeMwOSjSMFs4jsozgZxOyQKqXuW2e+3KcKqqlxZT02MeOxh5RGYx4iGJsOU+CIpAoVFoljW4TJBHp5TBpwu4Lgtw2Dx5lOo70Jk1QHgaKOuwVpCF5c10cqgCs6Qp00lQBAUYSFQpF3NVUrUCE02l0lmlpkk5is8SRDjBqIhytVcJdyKu6KAA

**Comment by sinclairzx81** [comment]
@orimay Hi, sorry for the delay, 

> Just noticed the latest release deprecating Type.Base. Just wanted to let you know that we still have this issue unresolved:

Yeah i know. I finally gave up and decided to deprecate Base (basically for the reasons above, as I think the type was a mistake) and reconciling operations around these class instances was just proving too complex when the entire TB compositor based on remapping structured objects (i.e. schemas). It doesn't fix this issue, rather it reduces the problem down to the Refine(...) function which itself produces a structured object compatible with the compositor.

```typescript
const T = Type.Refine({}, value => value instanceof Date)

// represented as keyword extension (to be replaced with 'x-refine' in later versions)

const T = { '~refine': [[(value => value instanceof Date, '...')]] }
```

Note that while it's still not possible to reflect into Refine(...) to learn what it is refining for, the `~refine` keyword does take an array of refinements, meaning an evaluated Intersect could stack the internal refinements.

```typescript
const A = Type.Refine({}, value => value instanceof Date)
const B = Type.Refine({}, value => value instanceof Date)
const C = Type.Evaluate(Type.Intersect([A, B]))

// ... evaluated Refine === stacked refinements (AND operations)

const C = { 
'~refine': [
   [value => value instanceof Date, '...'],
   [value => value instanceof Date, '...']
 ]
}

// ... and where C is representative of a 

type C = Date & Date // ... evaluated as Date
```

---

Based on the above idea, it should be possible to prototype the Refine / Evaluate on a TB fork (so will be doing that over the next while when I have the time (community help is welcome too!)), but deprecating Base now just narrows the problem down to the parts of the current API where I think a solution is the most promising (Unsafe/Refine)

Still working on this though! Happy to keep the discussion going!

**Comment by orimay** [comment]
@sinclairzx81 Hi, thanks for keeping the amazing project up!

I love your refinements stacking idea! Sounds amazing. 

I got a couple of ideas you might find interesting. Since we can infer guards, we can store that info in type as safely-inferred:
```typescript
import Type from 'typebox'

const safeType: unique symbol = Symbol();
type TypeTSafe<T> = { [safeType]: T };
function TypeTSafe<T>() {
  return {} as TypeTSafe<T>;
}

function TypeTGuarded<V>(cb: (v: unknown) => v is V) {
  return Type.Refine(TypeTSafe<V>(), cb);
}

const TSafeDate = TypeTGuarded(value => value instanceof Date);
/**
 * const TSafeDate: Type.TRefine<TypeTSafe<Date>>
 */
```

https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSgYwgDsBneRgQw1WTQC44BXesACOfdIyQhSAGzgBeOAGUJ0gBQBKANyVCaREQQL2qADwIAfHLgBvOAG02HLqgC6vBHAC+WjAJoxgDHpoBkamZurWlHBwUKgwfFD01h5wrIxBnIYcYVoe1D70fgFJTggA4nysUAAmqNXGAGrhNMS8KgBuvAIA1vQQAO70anIW7XDA6Q3DVlExcQklRAB0AEqoGMD0qCqlWSZN6gA0cC2alHm0DMyIewAirDDo8qUVVbXVHaxSoiNw7V8-TbMViFVAQDBwe6PM4AegAVHConCTld4CEOFDUG5lgg1hstqZ9HtjJizGYkTDKEA

It is also possible to make class instance types, that take a class as an argument and store its info:

```typescript
import Type from 'typebox'

function TypeTClass<T>(c: new (...args: unknown[]) => T) {
  return Type.Refine({ ['~class']: c }, v => v instanceof c);
}

const TSafeDate = TypeTClass(Date);
/**
 * const TSafeDate: Type.TRefine<{
 *   "~class": new (...args: unknown[]) => Date;
 * }>
 */
```
https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoSjAVwDsBjGYCexIhAYQBsBDAM4CAPAgB8ACkYAuOPVQB3OBIB0avlADmA2QwDW9CAvoBtALoBKOAF4xiKwG9KcOFFQxaUdsjQqASqgYwPISDnAmeAB+jPxCeGayjHAAvgA0cABuNnZZwQIwfEyoEBhwjBYA3JTJ1Ixs+YgAynwYqAAifDDo1hxo3LECEh1dlZQA9ABUE84TZfXwCM2tw6iyPqgqCAFB8sJOcLMuAETRA0ey8kqq6lo6cPqGxuZWtnArVQcpYjNjlEA

Either way, it may improve the DX for using classes with TypeBox, while also allow avoiding the discomfort of using `Type.TUnsafe` for not so unsafe cases. And I guess, both of these can be relatively easy handled for intersections. Do you have any thoughts on this?

p.s.
From what I just noticed, it seems Intersect doesn't even work with Unsafe:

```typescript
import Type, { StaticDecode } from 'typebox'

const TDate = Type.Unsafe<Date>({});

const schemaNonEvaluated = Type.Intersect([
  TDate,
  TDate,
]);
type TNonEvaluated = StaticDecode<typeof schemaNonEvaluated>;

/**
 *  const schemaNonEvaluated: Type.TIntersect<[Type.TUnsafe<Date>, Type.TUnsafe<Date>]>;
 *  type TNonEvaluated = Date;
 */

const schemaEvaluated = Type.Evaluate(schemaNonEvaluated);
type TEvaluated = StaticDecode<typeof schemaEvaluated>;

/**
 *  const schemaEvaluated: Type.TNever;
 *  type TEvaluated = never;
 *  
 *  instead of
 *  
 *  const schemaEvaluated: Type.TRefine<Type.TUnsafe<Date>>;
 *  type TEvaluated = Date;
 */
```

https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKYBo4G84GUYCGMwAxgCKokQAmqcAvnAGZQQhwDkMKqARhAA8OAKGFUAdgGd4CMkToBeRDwB0AVSkEmqADxyYqAHwAKLPQCUAblETpcSSQAWqEAQByEcQFEAbgQA2AK7y1HBKyGgqAJLiBlCSlDDGANrCcIj6GGkZ8ujCALpWwtxoiB7efkEhYXiExOSUNLolqBBM9k4u7p6+AcEG1IbWwgD0AFRjaWPptvAOzq7lvVUDAFzKkQgxcQkkMDrJEagqCBqSWrqZhphHJ2cXevKG+UNT6S1lPZX9qKFKmdY4GMRjZPHZ5l1lj8-htjlD5MYIYsvn0QkUPgh4QMavgiKQKFRaDoWm0OgsCFjfq9RhM3nBZmTId8Qutbgg3KgfKgoIDpnAMZSYeJOdzeek6cApAYCKE2nS6QykRTmWtYScAEqoJiS3Rs+7aR4GQyvIHvHiIQU1AFTEFAA

**Comment by orimay** [comment]
@sinclairzx81

**Comment by sinclairzx81** [comment]
@orimay Hi! Sorry again for the delay, still thinking about this issue (it's a difficult design problem!)

## Unsafe/Refine

> Either way, it may improve the DX for using classes with TypeBox, while also allow avoiding the discomfort of using Type.TUnsafe for not so unsafe cases. And I guess, both of these can be relatively easy handled for intersections. Do you have any thoughts on this?

Yeah. I think the Refine/Unsafe pairing do strike a fairly good balance. I note that historically, Unsafe has proven to be a very useful mechanism to enable TypeBox to integrate with legacy OpenAPI schematics, the most notorious schema being Nullable. 

```typescript
// this has proven to be exceptionally useful
const Nullable = <Type extends Type.TSchema>(type: Type) =>
  Type.Unsafe<Type.Static<Type> | null>({ ...type, nullable: true })
```

... but for Refine, there are actually still a few challenges regarding generality (specifically for direct schema augmentation - as would be needed for Nullable)

``` typescript
import Value from 'typebox/value'
import Type from 'typebox'

// nullable + validation refinement
const Nullable = <Type extends Type.TSchema>(type: Type) =>
  Type.Refine(Type.Unsafe<Type.Static<Type> | null>({ ...type, nullable: true }), 
    value => Value.Check(type, value) || value === null
      )

const T = Nullable(Type.String()) // { type: 'string', '~refine': () => { ... } }

Value.Parse(T, 'hello') // ok!

Value.Parse(T, null)    // error: "must be string"
                        //
                        // This is because TB observes keywords as 
                        // logical AND for `type`  and `~refine` which
                        // technically satisfies a "refinement", but 
                        // breaks for augmented schematics.
                        //
                        // { type: 'string' } AND { '~refine': () => { ..  } } <-- need OR check!
```

As of 1.x Refine is the only mechanism implemented (And), but have been considering whether a RefineOr/RefineAnd API would make sense. See the links below to see how TypeBox handles the current Refine checks ... and where a RefineOr would wrap the each logical expression in a `(refine-or || expression)` if a `~refine-or` keyword was present.

Build: https://github.com/sinclairzx81/typebox/blob/main/src/schema/engine/schema.ts#L231
Check: https://github.com/sinclairzx81/typebox/blob/main/src/schema/engine/schema.ts#L291
Errors: https://github.com/sinclairzx81/typebox/blob/main/src/schema/engine/schema.ts#L353

In all, I do think Refine is the right path, and a logical AND/OR version of it might enable TypeBox apply some static/type-level reasoning to the interior type ... it is worth exploring.

---

## Unsafe/Evaluate

> From what I just noticed, it seems ~~Intersect~~ Evaluate doesn't even work with Unsafe:

Yeah, this is expected. It is the same problem as Base where there is no way for TypeBox to make runtime structural call to determine if 2 Unsafe types are structurally equivalent.

```typescript
const A = Type.Unsafe<Date>({})
const B = Type.Unsafe<Uint8Array>({})
const T = Type.Intersect([A, B])

// Runtime
const R = Type.Evaluate(T)   // R = { ...A, ...B } <-- runtime sees this
```

This said, I would actually be a bit more open to exploring adding Unsafe to TB's Extends/Evaluate logic using the following rules.

```typescript
const A = Type.Unsafe<Date>({})
const B = Type.Unsafe<Uint8Array>({})
const T = Type.Intersect([A, B])

// Static
const R = Type.Evaluate(T)   // C: TUnsafe<Date & UInt8Array> ? 
```

.. but it would need some thinking about ... 

---

So really difficult design problems! As with the Base type, there really isn't a easy way to incorporate user defined schema and check logic in Evaluate as the type system is deriving everything from strict keyword semantics (JSON Schema), but I am still searching....

I think Refine works well for validation cases now, but for integration into Evaluate, that's going to take some thinking.

---

Let's keep this conversation going! :)

**Comment by orimay** [comment]
I see, thank you! But do we really need a structural comparison? If we have two unsafe, let's say, Date or UInt8Array types, we only care that they are the two Date or UInt8Array types, right? So this is what we should be getting:
```typescript
const A1 = Type.Unsafe<Date>({});
const A2 = Type.Unsafe<Date>({});
const B1 = Type.Unsafe<Uint8Array>({});
const B2 = Type.Unsafe<Uint8Array>({});
const T1 = Type.Intersect([A1, A2]);
const T2 = Type.Intersect([B1, B2]);
const T = Type.Intersect([A1, B1]);

// Static
const R1 = Type.Evaluate(T1); // R1: TUnsafe<Date>
const R2 = Type.Evaluate(T2); // R2: TUnsafe<UInt8Array>
const R = Type.Evaluate(T); // R: TUnsafe<Date & UInt8Array>
```

I think it must be safe to assume that
```typescript
TUnsafe<A> & TUnsafe<B> === TUnsafe<A & B>
```

At the very least, when `A === B`. But ideally, not only. Currently, it resolves to never 0_o

**Comment by sinclairzx81** [comment]
> I see, thank you! But do we really need a structural comparison? If we have two unsafe, let's say, Date or UInt8Array types, we only care that they are the two Date or UInt8Array types, right? So this is what we should be getting:

Yeah, unfortunately it's needed. Keep in mind that, TypeBox is attempting to model TypeScript's type system at runtime, and maintains a fairly large submodule written to symmetrically answer TS questions such as "does `X extends Y`?" ...

https://github.com/sinclairzx81/typebox/tree/main/src/type/extends
https://github.com/sinclairzx81/typebox/blob/main/src/type/extends/extends-left.ts
https://github.com/sinclairzx81/typebox/blob/main/src/type/extends/extends-right.ts

## Evaluate | Extends

These modules all perform structural comparisons against two known (Left, Right) JSON Schemas and get used throughout TypeBox to mirror TS evaluation behaviors. For example, Evaluate uses Extends in the following way ...

https://github.com/sinclairzx81/typebox/blob/mapped/src/type/engine/evaluate/compare.ts#L33-L73

... which enables Canonical Type Normalization of Logical type expressions (TS)

[TypeScript Link Here](https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAFQJ5gKZwGZQiOByGFVAIwgA88AoS1MyWOAYwgDsBneAbzgBkIBzYIwCGAGwA0cAMLCWrIWLgBfOAF5ERAHQBlRlGBgYACgAG1OHEJpeAhaLVxuZAFxwWAVxDFUUZXABkcEbcSK4eXj7KAD6OcABeYZ7evkoAlOaWRNKy8iL26gCiAG5i7sIwqAA8fIJ5AHyUJumUAPQtTKwcNrVirshomggAkiwVUGyojDCVANr9qIMA8sQAVpPTnK3tFhYuGgMIAHJJPgDcW8p1kvODAKoswKyzNwjLa1OVm207FqH7C0cTlBzt8lFd-ktVutPhcfgkIYCIsCLmCALp1dHUb7MdjwGRyB55PpaBD3R4sZ4kt7Qr7bHZ7F7HJEgum-YkHJnJFmXa5UqEfWk-OAMkmcs6wnbwxlA7lohqUKzoGp2Bw3bQwcpCSqKiAYbp2OpC76K-V5BybIWWq3Wm22izfXaJZmUO2ut120EBIIW92+v1wB1wP7hLku-3hj3tFQxbhhiPxy2B+Eh8UJtM-UHNBVZfG5RTqNUamBanV63OEsSGgPtE3llXqH3p9OBvYp5FNpuB4MyuMd+OemO9vvhltO0PDhNJsepicR0FAA)

```typescript
import Type from 'typebox'

export const { Logical, Canonical } = Type.Script(`

  type Logical = { x: number } & ({ y: number }| { z: number })

  type Canonical = Evaluate<Logical>
`)

// const Logical: Type.TIntersect<[Type.TObject<{
//     x: Type.TNumber;
// }>, Type.TUnion<[Type.TObject<{
//     y: Type.TNumber;
// }>, Type.TObject<{
//     z: Type.TNumber;
// }>]>]>

// const Canonical: Type.TUnion<[Type.TObject<{
//     x: Type.TNumber;
//     y: Type.TNumber;
// }>, Type.TObject<{
//     x: Type.TNumber;
//     z: Type.TNumber;
// }>]>

type Logical = Type.Static<typeof Logical>     // type Logical = {
                                               //   x: number;
                                               // } & ({
                                               //   y: number;
                                               // } | { 
                                               //   z: number;
                                               // })


type Canonical = Type.Static<typeof Canonical>  // type Canonical = {
                                                //   x: number;
                                                //   y: number;
                                                // } | {
                                                //   x: number;
                                                //   z: number;
                                                // }
```

The main issue with Unsafe is that TB cannot structurally compare the schematics (because it doesn't know what they are), and where a single schematic "could" represent two distinct types (Date, Uint8Array). There are only really two possible types Unsafe could be interpreted as:

- `TAny` - TypeBox gives up and just remaps `TUnsafe` to `TAny` as part of an evaluation (info-loss - permissive)
- `TNever` - TypeBox guards with `TUnsafe` to `TNever` indicating the TUnsafe couldn't be evaluated (current behavior)

Neither interpretation is ideal :(

---

## Nominal

It's really a difficult problem to solve. One approach I have been mulling is to maybe investigate some kind of Nominal typing support that might allow TypeBox to test if a type is Equal and Not-Equal (but not Extends!)

```typescript
const A = Type.Nominal<Uint8Array>({ type: 'Uint8Array' })  // Must implement `type` such that
const B = Type.Nominal<Date>({ type: 'Date' })              // Extends can compare for TNominal
```
That would enable custom types to participate in Extends checks (and be compat with Refine)

```typescript
// Extends checks guarded on Nominal
const C = Type.Refine(Type.Nominal<Date>({ type: 'Date' }), value => value instanceof Date)
```
Where Nominal would be a more constrained type of Unsafe.

Thoughts?

**Comment by orimay** [comment]
Hmm, this sounds really nice! It will even make it possible to have helpers for generic cases. I love it!

**Comment by sinclairzx81** [comment]
@orimay Hi!,

Hey, I am just doing some issue maintenance, and I may move this issue into discussions as the Base type is set for deprecation (which is what the original issue relates to), but I am keen to continue discussion on a potential Nominal(T). 

I will swap things over and rename the heading to "Nominal Type Discussion", and we can continue things from there. Will be looking at the Nominal type again once TB completes a round of Json Schema spec compliance work.
