### ISSUE TITLE
Help Wanted (Revision 0.32.0)

### ISSUE THREAD

**Issue by sinclairzx81** [sinclairzx81/typebox#694]
Hi,

TypeBox is currently pending a publish of a milestone revision (0.32.0) which seeks to offer dual publishing of CJS and ESM modules. The changes in this revision also include the full modularization of TypeBox's type system as well as dozens of new enhancements to the type system. Given the size and nature of this work, I'd like to reach out to the community to help test this revision prior to publishing. 

The development version of 0.32.0 can be installed with the following.

```
$ npm install @sinclair/typebox@dev
```
With the full change log for this revision located at the following.

https://github.com/sinclairzx81/typebox/blob/index/changelog/0.32.0.md

I'm mostly looking to learn of any possible breakage users experience on this revision (if any). Any breakage reported will be reviewed prior to publishing the revision. All general feedback is welcome too. Will be looking to publish between Friday 22nd and Sunday the 24th of December.

S

**Comment by sinclairzx81** [comment]
CC @loynoir @stuft2

**Comment by dwickern** [comment]
👍 Everything works on my end (using CJS)

**Comment by sinclairzx81** [comment]
@dwickern Hi, thank you for taking the time to test!

Sadly, didn't get a lot of community testing over the week as I'd hoped for (I guessing it's quite rare for people to check issue thread notices). Still, will be pushing out this revision this afternoon. Will be tracking any significant issues over the next few days, but hoping for the best! :)

Thanks again
S

**Comment by SuperKXT** [comment]
Upgrading to `0.32.3` broke `@fastify/type-provider-typebox` for me.
The generics don't seem to work properly and the types all default to `unkown`.

**Comment by sinclairzx81** [comment]
@SuperKXT Hi,

The `@fastify/type-provider-typebox` package was tested prior to release. It should be working fine (as the provider inference hasn't changed from 0.31.0 to 0.32.0). See link below where the provider is inferring types only available on 0.32.0.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMQIYGcbAGYE84ahEOAcg1XWyIChRJY4BvOAFSzAFMAaZ1tgIQgAeLdgAV8AN2AATNlDgBfXPkJEAAqTSYsAehg8AtGAnTZ+vewBGgqpQDGEAHZpcZLXAC8iV9gAUASgA6AHdgGAALYTYxCEkZKAAeSP4hHmjY2QA+f0pKDXIsAIBzNhgfIm0iLnpKODgUWzC2ECQALgYa2rhtbTgAWSQwdiludhQ4AHkHABscAEFxJGAppAsptjhgBzgAJTZJFGBHOAAGAIBmACYA447aqyksNsiA-sG2KR9npiawZZg2AAyoVkSCmZQsABJ6McAD4ARnkUNhCKR8MR0LRRD8XAA0h4MiM2AEAMowKCbQr+PwdeSUeRcHxQNgARz8+PatSZzIC9wKFmOApunJZPIgDx5grhHS5ovF-OOcKFcBlvIlCqltW6cACAWlItVFjhRo1cDpfiAA)

```typescript
import Fastify from 'fastify'
import { Type, TypeBoxTypeProvider } from '@fastify/type-provider-typebox'

const fastify = Fastify().withTypeProvider<TypeBoxTypeProvider>()

fastify.get('/', {
  schema: {
    // Mapped Types Only Available in Revision 0.32.0
    body: Type.Mapped(Type.TemplateLiteral('b${0|1}${0|1}${0|1}${0|1}'), K => Type.String())
  }
}, (req) => {
  req.body.b0000
  req.body.b0001
  req.body.b0010
  req.body.b0011
  // ..
  req.body.b1111
  
})
```
You could try delete the node_modules directory and install the packages. Also, just ensure you've only got 0.32.0 installed. Let me know if this helps.

Cheers
S

**Comment by SuperKXT** [comment]
Thank you for the quick response!

I have narrowed that the issue only happens if I import `Type` from typebox directly but does not happen if I import from `@fastify/type-provider-typebox`.

The issue does not happen in the playground, but I've created a minimal repro of the issue [here](https://github.com/superkxt/fastify-typebox-test).

Things I've tried:
- Remove the lock file and node_modules and reinstall.
- Use npm instead of pnpm.

**Comment by sinclairzx81** [comment]
@SuperKXT Hiya,

I wondering if this might be to do with the type provider requiring the updated peerDependency (which is currently locked at <= 0.31.0). This range is usually updated after a TB minor revision, but has yet to be done for 0.32.0.

https://github.com/fastify/fastify-type-provider-typebox/blob/main/package.json#L8

Running on the TSP, things still seem to resolve correctly.

[TypeScript Link Here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAMQIYGcbAGYE84ahEOAcg1XWyIChRJY4BvOAFSzAFMAhCADxfYAV8AN2AATNlDgBfXPkJEAAqTSYsAehis2AWjDCxE7ZvYAjHlRrR4jPm2myCxBSmAA7AMYAbJMCgatZtxUlO4Qrmi4ZKpwALyIUdgAFACUAHQA7sAwABa2ghAi4lAAPLZcvFr5hRIAfCmUlMrkWKkA5mwwiURqRAA0DJRwcCju2WwgSABcA0NDampwALJIYOyizFoocADyrp44AIJCPt4mnnZucABKbCIuYXAADKkAzABMqY+Ds2aiWNO2VLLVZsUSJQFMcZgbwwNgAGSyEiQni6JgAJPRHgAfACMUgx2LxBNx+MxJKIyX6AGlYjUNuxUgBlGBQNytFLJb5SShSfqJKBsACOyVpMzgAsFqV+LRMjzlXyGEqlED+UvlOO+SulaseOIV4qFytVst1GrmC1SqU1hu1Jhx9o1UmSQA)

Would you like to submit a PR to the Fastify Type Provider project to bump the peer dependency range?

**Comment by SuperKXT** [comment]
> Would you like to submit a PR to the Fastify Type Provider project to bump the peer dependency range?
Sure!

**Comment by AaronPorts** [comment]
Still having this issue with typebox: 0.32.4 and @fastify/type-provider-typebox: 3.6.0.

**Comment by sinclairzx81** [comment]
@AaronPorts Hi

Have just re-tested and things should be working ok on @fastify/type-provider-typebox: 3.6.0. I can only really recommend trying to clean out node_modules and reinstalling to ensure there's no transient older versions of TypeBox installed. My hunch is that TS may be having difficulty resolving for multiple installed versions of TypeBox, but outside of this, I don't have much additional information to go on.

Try re-install, and failing this, if you are able to setup a repro project, that would be helpful.

Let me know how you go

**Comment by sinclairzx81** [comment]
@SuperKXT @AaronPorts 

Ok, I've been able to resolve the issue by updating tsconfig.json to the following.

```typescript
{
   "module": "CommonJS",
   "moduleResolution": "node",
   "verbatimModuleSyntax": false,
}
```
The issue is, since 0.32.0, TypeBox has begun support for both CJS and ESM, however the Type Provider is CJS only. I believe the issue relates to TS trying to resolve types from the CJS definitions in the Provider (which work), but when importing `Type` from `@sinclair/typebox` AND configuring for `module: ESNext`, this will cause TS to resolve the ESM definitions (not the CJS definitions used by the provider).

The above tsconfig.json fix should ensures that module resolution is kept to CJS only (inline with the provider). Ill have a look for some other alternative solutions (Unfortunately, supporting ESM is not without it's challenges) :(

**Comment by sinclairzx81** [comment]
So, taking a deeper look into this, I don't think there's much that can be done TypeBox side to make things easier here, other than dropping support for ESM which is not really a viable option (as I had hoped to eventually drop support for CJS (one day)). 

For now you will need to configure your projects for module resolution Node10 and module CommonJS. As below.

```typescript
{
   "module": "CommonJS",
   "moduleResolution": "Node10",
   "verbatimModuleSyntax": false,
}
```

One possible solution outside of TypeBox might be to update the Type Provider to support both ESM and CJS (as TypeBox does), which would allow for both ESM and CJS TS configuration, however it's a bit of work to do this (as the tooling for dual publishing is quite bad), and any updates made to the Provider would likely need to pass through Fastify's TypeScript team, which given the nature of the issue, I would expect a PR to need a really good review and team consensus reached on how best to dual publish (I spent a few weeks working out the TB build, things are very complex). I haven't the bandwidth for this currently, but could potentially look at things semi early next year.

@AaronPorts Again, keep me posted if these configurations resolve things your side.

**Comment by AaronPorts** [comment]
@sinclairzx81 Yes, it resolves the issue, but I have some packages (like `got` for ex.) that require esm. So this workaround is not drop in replacement in my case.

**Comment by sinclairzx81** [comment]
@AaronPorts Thanks for getting back

Hmmm, Not too sure what could be done TypeBox side as it "should" be configured correctly. The following links show the resolution TS uses for various module configurations. 

[TypeBox Resolution](https://arethetypeswrong.github.io/?p=%40sinclair%2Ftypebox%400.32.4)

![image](https://github.com/sinclairzx81/typebox/assets/3048342/620d739a-f85a-4964-8329-a88e7be76740)

[TypeProvider Resolution](https://arethetypeswrong.github.io/?p=%40fastify%2Ftype-provider-typebox%403.6.0)

![image](https://github.com/sinclairzx81/typebox/assets/3048342/7af4763c-56b7-4ee3-9f9d-6eb0dcfaa0e4)

As you can see, the Provider is resolving CJS despite configurations for Node16 (ESM). This would suggest the Provider does need updating to support ESM resolution for Node16. If this was done, it should resolve this issue, however it's likely going to require the Provider to dual publish (which unfortunately is less trivial than it should be)

Would you like to draft an issue on the Type Provider package?

**Comment by sinclairzx81** [comment]
@AaronPorts Have submitted a PR to have this resolved. 

Given the holiday period, it may take some time to merge. If you can get by with the CommonJS configuration in the interim, that should hold until things get merged downstream, alternatively, just keep on with 0.31.0.

**Comment by sinclairzx81** [comment]
@SuperKXT @AaronPorts Hiya, 

Looks like the Type Provider updates were published this morning. You can install the following which should solve ESM configuration issues.

```typescript
@fastify/type-provider-typebox@4.0.0
@sinclair/typebox@0.32.4
```
Have tested locally and things should be ok, but if you run into any issues, please let me know (I'm currently in the process of chasing down and documenting ESM issues, so any issues reported are very helpful)

Cheers!

**Comment by SuperKXT** [comment]
Heroic! Thank you! Will revisit this discussion if I encounter any other issues.
