### ISSUE TITLE
Recursive type support

### ISSUE THREAD

**Issue by JamieMagee** [sinclairzx81/typebox#71]
I have some types which define recursive logical operations:

```ts
type Operator = 'and' | 'or';
type Operand = {
  name: 'operandA' | 'operandB' | 'operandC';
};
export type Condition = {
  operator: Operator;
  operands: Array<Condition | Operand>;
};
```

Which allows me to define a condition like this:

```ts
const condition: Condition = {
  operator: 'and',
  operands: [
    {
      name: 'operandA',
    },
    {
      operator: 'or',
      operands: [
        {
          name: 'operandB',
        },
        {
          name: 'operandC',
        },
      ],
    },
  ],
};
```

Which is equivalent to `operandA and (operandB or operandC)`

Is this representation currently possible with typebox?

**Comment by sinclairzx81** [comment]
@JamieMagee Hi. Currently TypeBox doesn't support recursive types as you would imagine them. There are some suggestions for adding a `Type.Ref(...)` API which should also help to make this possible, but at this stage the API is still under consideration. (Primarily focusing on shared schema reuse). You can read a bit about it here. https://github.com/sinclairzx81/typebox/pull/61

@dwickern Just chiming you you in on this one to get some thoughts.

That said, the following shows what is and isn't currently possible in TypeBox today. Link [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgFQJ5gKYBo4GUYCGMwAxjsriQBYYgFwC+cAZlBCHAOQACAzsADsSAGwLAoAehjoMAIwgAPTgChlEiXAC02nbr36Dho8b1qNABQi9+s4RjgAKAKIKww0sBgBKM1pP+AwKNVEggBXngAeUwoImg4AF44AB5kOAwFGAwBABNeLgJczjgAHy5oYrLODABHAFcCYV5OAD4HCAAuFC9ElpQZADoAGU8MWOF2n2VQ8PgXMCgMa2AwxJTlODgh9MzsvJRKGjocDbhInazc-IpqWgIsU4AlC73rw7uTtuEuoZxOs5wUC6jx6CT6CFOixgdSgAn6mAGyDqbgwDgA2sI-oCALo+Bi+ABignsvAgcGEYQA5nACPkYDQ4LwqARMHAIMw4PT7BkFkt+KtgPkANYCCAAdzhghpOQAboUSBgBtMwhEUGt5otlmEHKc0AiRllxg4YFA6hgvCdNtExnEoA5OIUcpwLXBThq+SsBDrNps9YqDTaJpwaMIKc7LT7rbEYNB7bUGk1w66ffD-aMjZwxdBhE6XacfFNpKy0kl8ERSMkixh2SgWmZfGiTWacAAiR0tnBolshikduAt+ONXh9ltZqA5lvY7H13xBOfz-y+ADCMMWAhgwlQcAAchB4JZlrYMLOF6ez9pVIJDcwCAq4ABBXDIXc5ewQzai1+8LqP58QV9otO+LKrMD5Pi+9hJH6AyRLIABWGAkDADjvnA6hwCQhSivAvAYMIHKLMwYzZAqAxwAA6hAdQ5nAiz1OI9jQfeUCxKgDjQY8GDMA4Dign0v4QV4Pgfv+SxdExLEEGxAmiT06FjGwUDKAwXhAA)

```typescript
import { Type, Static, TSchema } from '@sinclair/typebox'

// ------------------------------------------------------------
// Possible (Explicit)
// ------------------------------------------------------------

const Operator = <T extends 'and' | 'or' | 'equals'>(o: T) => Type.Literal(o)

const Expression = <
  L extends TSchema, 
  O extends TSchema,
  R extends TSchema, 
>(l: L, o: O, r: R) => {
  return Type.Tuple([l, o, r])
}
// Fine so long as the shape of the expression is known in advance.
const T = Expression(
  Type.Literal(true), 
  Operator('and'), 
  Expression(
    Type.Literal('hello'), 
    Operator('equals'), 
    Type.Literal('world'), 
  )
)

type T = Static<typeof T>
//
// [true, "and", ["hello", "equals", "world"]]
//

// ------------------------------------------------------------
// Currently Not Possible
// ------------------------------------------------------------

interface ASTNode {
  nodes: ASTNode[]
}

const ASTNode = Type.Object({
  // cannot self reference. Would require Type.Array(Type.Ref(() => ASTNode))
  nodes: Type.Array(ASTNode) // error
})
```

**Comment by JamieMagee** [comment]
Thanks for the quick response. Unfortunately I won't know the shape of the data ahead of time, and the expressions can be arbitrarily deep. I'm also not sure that `Type.Ref(...)` is a solution either.

Looking at the solutions [`zod`](https://github.com/colinhacks/zod#recursive-types) and [`io-ts`](https://github.com/gcanti/io-ts/blob/master/index.md#recursive-types) came up with for this problem, they both settled on lazy evaluation with a static type as a hint. However, neither of those has native support for exporting to JSON schema ([`io-ts` has it as an open issue for 2+ years](https://github.com/gcanti/io-ts/issues/197), and [`zod` declared it out of scope](https://github.com/colinhacks/zod/issues/331) and a user created [`zod-to-json-schema`](https://www.npmjs.com/package/zod-to-json-schema))

**Comment by dwickern** [comment]
I just updated #61 to support recursion via `Type.Ref(() => ReferencedSchema)`

Recursion does necessarily involve `$ref` because that's the only way to encode recursion in JSON Schema. On the typescript side, you need some explicit type annotations to make things work, which can be clunky.

Here's how I implemented `Condition`:

https://github.com/sinclairzx81/typebox/blob/70cae4766b09fb1e911de51a074ecb9423fff14a/spec/schema/ref.ts#L104-L153

And the resulting JSON Schema:

```json
{
  "$id": "condition",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "operator": {
      "enum": [
        "and",
        "or"
      ]
    },
    "operands": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "name": {
                "enum": [
                  "operandA",
                  "operandB",
                  "operandC"
                ]
              }
            },
            "required": [
              "name"
            ]
          },
          {
            "$ref": "condition"
          }
        ]
      }
    }
  },
  "required": [
    "operator",
    "operands"
  ]
}
```

**Comment by JamieMagee** [comment]
Wow! Yes, that exactly solves my problem. Thank you so much.

I'll consider this issue closed when #61 is merged.

**Comment by sinclairzx81** [comment]
@JamieMagee  Hi, have just published preliminary support for Recursive Types on `0.17.6`. The following will describe a AST like binary expression node using TypeBox. Additional documentation can be found https://github.com/sinclairzx81/typebox#Recursive-Types

```typescript
const Operator = Type.Union([
    Type.Literal('+'),
    Type.Literal('-'),
    Type.Literal('/'),
    Type.Literal('*')
])

type BinaryExpression = Static<typeof BinaryExpression>

const BinaryExpression = Type.Rec(Self => Type.Object({
    left:     Type.Union([Self, Type.Number()]), // number or expression
    right:    Type.Union([Self, Type.Number()]), // number or expression
    operator: Operator
}))

function evaluate(expression: BinaryExpression) {
    const left  = expression.left  as BinaryExpression | number // manual type assertion required
    const right = expression.right as BinaryExpression | number // manual type assertion required
}
```

Unfortunately, I still don't have a solution to statically infer the appropriate type for recursive types (in the above, we expect `left` and `right` of `BinaryExpression` to be either `BinaryExpression | number`. The TypeScript recursion limits seem to be unavoidable. As such, TypeBox currently defaults to `any`, which means you need to explicitly type assert (as per the `evaluate()` method above).

Currently the `Type.Rec(...)`, `Type.Box(...)` and `Type.Ref(...)` API's are all flagged as experimental at this stage. But should be good to produce the JSON schema you need. Will be open to suggestions on improving the current API's and certainly happy to discuss the current design of them. But lets do that in another issue thread.

Will close off this issue.
Cheers
S

**Comment by CharlieDigital** [comment]
Hey there, a followup question on this example.  I am using Typebox via Elysia's `t` utility wrapper.  I have been able to get this to correctly generate an output OpenAPI spec that is almost there.

If I do this:

```ts
const BinaryExpression = t.Recursive((Self) =>
  t.Object({
    left: t.Union([Self, t.Number(), t.Ref("bex")]), // number or expression
    right: t.Union([Self, t.Number(), t.Ref("bex")]), // number or expression
    operator: Operator,
  })
);
```

The resultant OpenAPI spec:

```json
  "components": {
    "schemas": {
      "bex": {
        "$id": "T0",
        "type": "object",
        "properties": {
          "left": {
            "anyOf": [
              {
                "$ref": "T0"
              },
              {
                "type": "number"
              },
              {
                "$ref": "bex"
              }
            ]
          },
          "right": {
            "anyOf": [
              {
                "$ref": "T0"
              },
              {
                "type": "number"
              },
              {
                "$ref": "bex"
              }
            ]
          },
          "operator": {
            "anyOf": [
              {
                "const": "+",
                "type": "string"
              },
              {
                "const": "-",
                "type": "string"
              },
              {
                "const": "/",
                "type": "string"
              },
              {
                "const": "*",
                "type": "string"
              }
            ]
          }
        },
        "required": [
          "left",
          "right",
          "operator"
        ]
      }
    }
  }
```

The resultant type generated (via Kubb):

```ts
export type Bex = {
  left: T0 | number | Bex
  right: T0 | number | Bex
  operator: string | string | string | string
}
```

The objective in this case is that `T0` is replaced with `bex`.  What would be the correct construct in this case to annotate `Self`?

I can leave off the `Self` which will generate the correct types on the schema, but the server side type is then incorrect (I can possibly create two types here? 1 for the payload, 1 for the server?):

```ts
const BinaryExpression = t.Recursive((Self) =>
  t.Object({
    left: t.Union([t.Number(), t.Ref("bex")]),
    right: t.Union([t.Number(), t.Ref("bex")]),
    operator: Operator,
  })
);
```
